import type { Dictionary } from './i18n.ts';

/** Russian UI strings. Keys are the English texts used in the source. DIRECT / PROXY / PAC stay untranslated (PAC keywords). */
export const ru: Dictionary = {
  plurals: {
    rule: ['правило', 'правила', 'правил'],
    duplicate: ['дубликат', 'дубликата', 'дубликатов'],
  },
  strings: {
    // tabs / header
    Proxy: 'Прокси',
    Rules: 'Правила',
    Settings: 'Настройки',
    'Proxy on / off': 'Прокси вкл / выкл',
    // status
    Status: 'Статус',
    Mode: 'Режим',
    Proxies: 'Прокси',
    ACTIVE: 'АКТИВЕН',
    OFF: 'ВЫКЛ',
    ON: 'ВКЛ',
    PENDING: 'ОЖИДАНИЕ',
    ERROR: 'ОШИБКА',
    '{mode} + rules': '{mode} + правила',
    Direct: 'Напрямую',
    direct: 'напрямую',
    proxy: 'прокси',
    pac: 'PAC',
    'Updated {when}': 'Обновлён {when}',
    'Not downloaded yet': 'Ещё не загружен',
    'Grant access': 'Разрешить доступ',
    'Access was not granted.': 'Доступ не предоставлен.',
    never: 'никогда',
    'just now': 'только что',
    '{n} s ago': '{n} с назад',
    '{n} min ago': '{n} мин назад',
    '{n} h ago': '{n} ч назад',
    '{n} d ago': '{n} д назад',
    '{n} B': '{n} Б',
    '{n} KB': '{n} КБ',
    '{n} MB': '{n} МБ',
    // errors
    'PAC fetch failed': 'Не удалось загрузить PAC',
    'PAC compilation failed': 'Ошибка сборки PAC',
    'Proxy config rejected': 'Chrome отклонил настройки прокси',
    'Invalid proxy': 'Неверный прокси',
    'Invalid domain rule': 'Неверное правило домена',
    'Proxy controlled by another extension': 'Прокси управляется другим расширением',
    'Proxy error': 'Ошибка прокси',
    '+{n} more': 'Ещё {n}',
    // home
    'Current site': 'Текущий сайт',
    'Add to list:': 'Добавить в список:',
    subdomains: 'поддомены',
    'Include subdomains': 'Включая поддомены',
    'Default for unlisted sites': 'Для сайтов вне списка',
    'Default mode': 'Режим по умолчанию',
    'Unlisted sites go direct. Only rules send traffic through the proxy.':
      'Сайты вне списка идут напрямую. Через прокси идут только сайты из правил.',
    'Unlisted sites use your proxies. Rules can force DIRECT.':
      'Сайты вне списка идут через ваши прокси. Правила могут принудительно отправить сайт напрямую (DIRECT).',
    'Unlisted sites are decided by your enabled PAC sources.':
      'Для сайтов вне списка решают включённые PAC-источники.',
    'Proxy servers (failover order)': 'Прокси-серверы (порядок переключения)',
    'Proxy address': 'Адрес прокси',
    'No proxy servers yet': 'Прокси-серверов пока нет',
    'Enable {x}': 'Включить {x}',
    'Move up': 'Выше',
    'Move down': 'Ниже',
    Remove: 'Удалить',
    Add: 'Добавить',
    'rule {x}': 'правило {x}',
    'default ({mode} mode)': 'по умолчанию (режим: {mode})',
    'Proxy is OFF': 'Прокси выключен',
    'no proxy enabled': 'нет включённого прокси',
    'no PAC source enabled': 'нет включённого PAC-источника',
    'plain host name': 'простое имя хоста',
    // PAC tab
    PAC: 'PAC',
    'PAC sources': 'PAC-источники',
    '+ Add': '+ Добавить',
    'Enabled sources are combined in this order: the first one that answers with something other than DIRECT wins. Scripts are embedded as data in the PAC given to Chrome; they never run inside the extension.':
      'Включённые источники опрашиваются по порядку: побеждает первый, чей ответ не DIRECT. Скрипты встраиваются как данные в PAC для Chrome и никогда не выполняются внутри расширения.',
    "Use my proxy servers instead of the PAC's own": 'Использовать мои прокси вместо прокси из PAC',
    'If a PAC script answers with a proxy, answer with the servers from the Proxy tab instead (DIRECT failover as set in Settings). Useful for generic lists that hard-code 127.0.0.1:1080.':
      'Если PAC-скрипт отвечает «идти через прокси», подставлять серверы с вкладки «Прокси» (с запасным DIRECT, как в настройках). Нужно для общих списков, где прописан адрес 127.0.0.1:1080.',
    'No PAC sources. Add a URL or paste a script.': 'Нет PAC-источников. Добавьте URL или вставьте скрипт.',
    inline: 'встроенный',
    'failed: {e}': 'ошибка: {e}',
    'not downloaded': 'не загружен',
    ok: 'ок',
    Delete: 'Удалить',
    'Sure?': 'Точно?',
    Update: 'Обновить',
    Edit: 'Изменить',
    'Download now': 'Загрузить сейчас',
    'Inline scripts have nothing to download': 'У встроенных скриптов нечего загружать',
    'Update failed (kept the previous version).': 'Не удалось обновить (оставлена предыдущая версия).',
    'Updated.': 'Обновлено.',
    'Already up to date.': 'Уже актуально.',
    'Inline script · {size}': 'Встроенный скрипт · {size}',
    'Updated {when} · {every}': 'Обновлён {when} · {every}',
    'Saved {when}': 'Сохранён {when}',
    'Manual only': 'Только вручную',
    'Every 15 min': 'Каждые 15 мин',
    'Every hour': 'Каждый час',
    'Every 6 hours': 'Каждые 6 часов',
    'Every day': 'Каждый день',
    'Add PAC source': 'Добавить PAC-источник',
    'Edit PAC source': 'Изменить PAC-источник',
    Name: 'Название',
    'Corporate PAC': 'Рабочий PAC',
    Type: 'Тип',
    'Inline script': 'Встроенный скрипт',
    'PAC URL': 'URL PAC',
    'PAC script': 'PAC-скрипт',
    Refresh: 'Обновление',
    Script: 'Скрипт',
    Save: 'Сохранить',
    Cancel: 'Отмена',
    'Name is required.': 'Укажите название.',
    'Enter a valid http(s) URL.': 'Введите корректный http(s) URL.',
    'Invalid script: {r}': 'Некорректный скрипт: {r}',
    'Downloading…': 'Загрузка…',
    'Download failed. See the status badge.': 'Загрузка не удалась. Подробности — в статусе источника.',
    'Downloaded.': 'Загружено.',
    // rules tab
    'Loading…': 'Загрузка…',
    'No rules yet. Add one or import a list.': 'Правил пока нет. Добавьте правило или импортируйте список.',
    'Nothing matches.': 'Ничего не найдено.',
    '{a} of {b}': '{a} из {b}',
    'Search domains…': 'Поиск доменов…',
    'Search rules': 'Поиск правил',
    'example.com or *.example.com': 'example.com или *.example.com',
    'New rule': 'Новое правило',
    'Action for new rule': 'Действие для нового правила',
    'Invalid domain: {e}': 'Неверный домен: {e}',
    'Bulk action': 'Массовое действие',
    'Set action…': 'Назначить действие…',
    'Delete {n}?': 'Удалить {n}?',
    Enable: 'Включить',
    Disable: 'Выключить',
    '{n} selected': 'Выбрано: {n}',
    'Select all shown': 'Выбрать все найденные',
    'Select rule': 'Выбрать правило',
    'Select {x}': 'Выбрать {x}',
    'Action for {x}': 'Действие для {x}',
    Enabled: 'Включено',
    'Sort by {x}': 'Сортировать: {x}',
    Domain: 'Домен',
    Action: 'Действие',
    On: 'Вкл',
    Import: 'Импорт',
    Export: 'Экспорт',
    'Import rules': 'Импорт правил',
    'Rules to import': 'Правила для импорта',
    'google.com\nyoutube.com PROXY\n*.example.org DIRECT\n# comments are ignored':
      'google.com\nyoutube.com PROXY\n*.example.org DIRECT\n# комментарии игнорируются',
    'Import from file': 'Импорт из файла',
    'Default action': 'Действие по умолчанию',
    Preview: 'Проверить',
    'Parsing…': 'Разбор…',
    'Saving…': 'Сохранение…',
    'Import {n}': 'Импортировать {n}',
    '{rules} ({fresh} new, {over} overwrite)': '{rules} ({fresh} новых, {over} перезапишут существующие)',
    '{n} invalid': 'некорректных: {n}',
    'line {n}: {e} — {text}': 'строка {n}: {e} — {text}',
    '{kb} KB pasted. Press Preview.': 'Вставлено {kb} КБ. Нажмите «Проверить».',
    '{name} loaded ({kb} KB). Press Preview.': 'Файл {name} загружен ({kb} КБ). Нажмите «Проверить».',
    Close: 'Закрыть',
    'Test a host': 'Проверить хост',
    'test host: mail.example.com': 'проверить хост: mail.example.com',
    'Enter a host name': 'Введите имя хоста',
    '→ {a} via {v}': '→ {a} по правилу {v}',
    '→ no rule: default mode applies': '→ правила нет: действует режим по умолчанию',
    // settings
    Behaviour: 'Поведение',
    'Fall back to DIRECT if the proxy is down': 'Идти напрямую (DIRECT), если прокси недоступен',
    'Appends "; DIRECT" to proxy chains': 'Добавляет «; DIRECT» в конец цепочки прокси',
    'Bypass proxy for plain host names': 'Не использовать прокси для простых имён хостов',
    'Names without a dot (intranet, localhost) go DIRECT unless a rule matches':
      'Имена без точки (intranet, localhost) идут напрямую, если нет подходящего правила',
    Appearance: 'Оформление',
    Theme: 'Тема',
    Language: 'Язык',
    System: 'Системная',
    Light: 'Светлая',
    Dark: 'Тёмная',
    Maintenance: 'Обслуживание',
    'Open with {key} · change in chrome://extensions/shortcuts':
      'Открывается по {key} · изменить: chrome://extensions/shortcuts',
    'No shortcut set · chrome://extensions/shortcuts': 'Сочетание не задано · chrome://extensions/shortcuts',
    'Re-apply now': 'Применить заново',
    'Export diagnostics': 'Экспорт диагностики',
    'Saved. The file contains no domains, hosts or URL paths.':
      'Сохранено. В файле нет доменов, хостов и путей URL.',
    'Applied.': 'Применено.',
    'Nothing to apply.': 'Нечего применять.',
    'Import from PAC Proxy Manager 1.x': 'Импорт из PAC Proxy Manager 1.x',
    'Paste the JSON produced by the export snippet in MIGRATION.md.':
      'Вставьте JSON, полученный скриптом экспорта из MIGRATION.md.',
    'Import failed: {e}': 'Ошибка импорта: {e}',
    'Imported: {r} rules, {p} proxies, {s} PAC scripts.':
      'Импортировано: правил — {r}, прокси — {p}, PAC-скриптов — {s}.',
    'Notes: {n}': 'Примечания: {n}',
    'v{v} · no analytics, no browsing history, no remote code':
      'v{v} · без аналитики, без истории посещений, без удалённого кода',
  },
};
